# Generated by Django 4.2.1 on 2023-05-22 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toggle',
            old_name='eve_play',
            new_name='eve_sleep',
        ),
        migrations.RenameField(
            model_name='toggle',
            old_name='mor_depart',
            new_name='mor_pathfind',
        ),
        migrations.CreateModel(
            name='MorningWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='weather', max_length=15)),
                ('text', models.CharField(default='오늘의 날씨 알려주기', max_length=15)),
                ('turn', models.IntegerField(default=1)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MorningTodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='todo', max_length=15)),
                ('text', models.CharField(default='오늘의 할일 브리핑', max_length=15)),
                ('turn', models.IntegerField(default=1)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MorningPathfind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='destination', max_length=15)),
                ('text', models.CharField(default='목적지까지 길찾기', max_length=15)),
                ('turn', models.IntegerField(default=1)),
                ('dest_list', models.TextField(null=True)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MorningDestList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('link', models.CharField(default='', max_length=150)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
