# Generated by Django 4.2.1 on 2023-05-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toggle',
            name='aft_nap',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='toggle',
            name='aft_todo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='toggle',
            name='aft_whitenoise',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='toggle',
            name='eve_health',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='toggle',
            name='eve_play',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='toggle',
            name='eve_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='toggle',
            name='eve_question',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='toggle',
            name='eve_todo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='toggle',
            name='mor_depart',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='toggle',
            name='mor_dest',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='toggle',
            name='mor_todo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='toggle',
            name='mor_weather',
            field=models.IntegerField(default=0),
        ),
    ]
