# Generated by Django 4.2.1 on 2023-05-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MorningDestList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=100)),
                ('latitude', models.CharField(default='', max_length=20)),
                ('longtitude', models.CharField(default='', max_length=20)),
                ('url', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='MorningMusicList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('link', models.CharField(default='', max_length=150)),
            ],
        ),
    ]
