# Generated by Django 4.2.1 on 2023-05-23 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_morningdestlist_morningmusiclist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afternoonblock',
            name='text',
            field=models.CharField(default='오늘의 날씨 알려주기', max_length=30),
        ),
        migrations.AlterField(
            model_name='eveningblock',
            name='text',
            field=models.CharField(default='오늘의 날씨 알려주기', max_length=30),
        ),
        migrations.AlterField(
            model_name='morningblock',
            name='text',
            field=models.CharField(default='오늘의 날씨 알려주기', max_length=30),
        ),
    ]
