# Generated by Django 4.2.1 on 2023-05-23 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_afternoonblock_text_alter_eveningblock_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='afternoonblock',
            name='link',
            field=models.CharField(default='', max_length=150),
        ),
    ]
