# Generated by Django 4.2.1 on 2023-05-24 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_afternoonblock_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afternoonblock',
            name='link',
        ),
        migrations.RemoveField(
            model_name='afternoonblock',
            name='playlists',
        ),
        migrations.RemoveField(
            model_name='eveningblock',
            name='playlists',
        ),
        migrations.RemoveField(
            model_name='morningblock',
            name='dest_list',
        ),
        migrations.RemoveField(
            model_name='morningblock',
            name='playlists',
        ),
        migrations.AlterField(
            model_name='morningmusiclist',
            name='link',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
