# Generated by Django 4.2.1 on 2023-05-24 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_afternoonblock_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfternoonStudyMusicList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('link', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EveningSleepMusicList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('link', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
