# Generated by Django 4.2.1 on 2023-05-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_afternoonstudymusiclist_eveningsleepmusiclist'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodMorning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=50)),
                ('weather_turn', models.IntegerField(default=1)),
                ('todo_turn', models.IntegerField(default=1)),
                ('music_turn', models.IntegerField(default=1)),
            ],
        ),
    ]
