# Generated by Django 4.2.1 on 2023-05-24 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_goodmorning'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toggle',
            old_name='mor_pathfind',
            new_name='mor_music',
        ),
        migrations.RemoveField(
            model_name='goodmorning',
            name='music_turn',
        ),
        migrations.RemoveField(
            model_name='goodmorning',
            name='todo_turn',
        ),
        migrations.RemoveField(
            model_name='goodmorning',
            name='weather_turn',
        ),
    ]
