# Generated by Django 4.2.1 on 2023-05-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_mor_pathfind_toggle_mor_music_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodmorning',
            name='music',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='goodmorning',
            name='todo',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='goodmorning',
            name='weather_turn',
            field=models.IntegerField(default=1),
        ),
    ]
