# Generated by Django 4.2.1 on 2023-05-24 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_goodmorning_music_goodmorning_todo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodmorning',
            old_name='music',
            new_name='music_turn',
        ),
        migrations.RenameField(
            model_name='goodmorning',
            old_name='todo',
            new_name='todo_turn',
        ),
    ]
