# Generated by Django 4.2.1 on 2023-05-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_music_goodmorning_music_turn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MorningMusicName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.IntegerField(default=1)),
                ('names', models.TextField(null=True)),
            ],
        ),
    ]
