# Generated by Django 4.2.1 on 2023-05-24 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_afternoonstudymusiclist_link_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AfternoonBlock',
        ),
        migrations.DeleteModel(
            name='EveningBlock',
        ),
        migrations.DeleteModel(
            name='MorningBlock',
        ),
        migrations.DeleteModel(
            name='Toggle',
        ),
    ]
