# Generated by Django 4.2.1 on 2023-05-24 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_delete_afternoonblock_delete_eveningblock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='morningmusicname',
            name='names',
        ),
        migrations.AddField(
            model_name='morningmusicname',
            name='name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.morningmusiclist'),
        ),
    ]
