# Generated by Django 4.2.1 on 2023-05-24 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_morningmusicname_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MorningMusicName',
        ),
    ]
