# Generated by Django 4.2.1 on 2023-05-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_delete_morningmusicname'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodAfternoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_turn', models.IntegerField(default=1)),
                ('study_turn', models.IntegerField(default=1)),
                ('nap_turn', models.IntegerField(default=1)),
            ],
        ),
    ]
