# Generated by Django 4.2.1 on 2023-05-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_goodafternoon'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodafternoon',
            name='nap_link',
            field=models.CharField(default='', max_length=150),
        ),
    ]
