# Generated by Django 4.2.1 on 2023-05-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_goodafternoon_nap_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodEvening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=50)),
                ('today_feedback_turn', models.IntegerField(default=1)),
                ('tomorrow_brief_turn', models.IntegerField(default=1)),
                ('health_turn', models.IntegerField(default=1)),
            ],
        ),
    ]
