# Generated by Django 4.2.1 on 2023-05-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_goodevening'),
    ]

    operations = [
        migrations.CreateModel(
            name='EveningDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary_turn', models.IntegerField(default=1)),
                ('brainer_turn', models.IntegerField(default=1)),
            ],
        ),
    ]
