# Generated by Django 4.2.1 on 2023-05-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_eveningdiary'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodmorning',
            name='pathfind_turn',
            field=models.IntegerField(default=1),
        ),
    ]
