# Generated by Django 4.2.1 on 2023-05-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_goodmorning_pathfind_turn'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfternoonBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('text', models.CharField(default='', max_length=50)),
                ('turn', models.IntegerField(default=1)),
                ('link', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EveningBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('text', models.CharField(default='', max_length=50)),
                ('turn', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='MorningBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('text', models.CharField(default='', max_length=50)),
                ('turn', models.IntegerField(default=1)),
            ],
        ),
        migrations.RenameField(
            model_name='morningdestlist',
            old_name='url',
            new_name='link',
        ),
    ]
