# Generated by Django 4.2.1 on 2023-05-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_afternoonblock_eveningblock_morningblock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfternoonNapMusicList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('link', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='goodafternoon',
            name='nap_link',
        ),
    ]
