# Generated by Django 4.2.1 on 2023-05-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_afternoonnapmusiclist_remove_goodafternoon_nap_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='afternoonblock',
            name='sleep_time',
            field=models.IntegerField(default=6, null=True),
        ),
    ]
