# Generated by Django 4.2.1 on 2023-05-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_afternoonblock_sleep_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodafternoon',
            name='sleep_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='afternoonblock',
            name='sleep_time',
            field=models.IntegerField(null=True),
        ),
    ]
