# Generated by Django 4.2.1 on 2023-05-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_goodafternoon_sleep_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodafternoon',
            name='sleep_turn',
            field=models.IntegerField(default=1),
        ),
    ]
