# Generated by Django 4.2.1 on 2023-05-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_goodafternoon_sleep_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='afternoonnapmusiclist',
            name='nap_time',
            field=models.IntegerField(null=True),
        ),
    ]
